### ISSUE TITLE
提个小建议，上传demo的时候，可以把IOS,Android文件夹下的编译产物删除

### ISSUE THREAD

**Issue by james-bltg** [wyswill/clourMusic_flutter#1]
我在下载Demo的时候，如果网不好，经常是下载不下来的。我下载很多次，都没有成功。昨晚两点起来后，想起有这么个事，又来下载。终于下载成功了，一看300多M，确实太大了。

所以，提个小建议，可以把IOS,Android文件夹下的编译产物删除。这样demo的大小只有几百kb，很方便上传和下载。

具体的做法，新建一个flutter项目，不要编译。然后和已有项目对比，哪些文件夹是编译后生成的，一目了然。

**Comment by wyswill** [comment]
好的
